import { VerticalBox, HorizontalBox, LineEdit, ScrollView } from "std-widgets.slint";
import { Theme, StyledInput } from "theme.slint";
export { Theme }

export struct ActionItem {
    name: string,
    exec: string,
    keywords: string,
}

export component LauncherWindow inherits Window {
    width: Theme.width;
    height: Theme.height;
    title: "Swift Launcher";
    no-frame: true;
    background: transparent;

    in-out property <string> search-text;
    in-out property <[ActionItem]> actions;
    in-out property <int> selected: 0;

    callback action-clicked(int);
    callback linefinished(string);
    callback accepted();
    callback quit();
    callback search-changed(string);

    forward-focus: runner;

    Rectangle {
        background: Theme.background-color;
        border-radius: Theme.border-radius;
        border-color: Theme.border-color;
        border-width: Theme.border-width;
        
        VerticalBox {
            padding: 20px;
            spacing: 10px;

            runner := StyledInput {
                // font-size: 10px;
                // horizontal-alignment: left; 
                // placeholder-text: "Type to search...";
                // text <=> search-text;

                key-pressed(event) => {
                    if (event.text == Key.Escape) {
                        root.quit();
                        return EventResult.accept;
                    }
                    if (event.text == Key.DownArrow) {
                        if (selected > -1) {
                            selected = selected + 1;
                        }
                    }
                    if (event.text == Key.UpArrow) {
                        if (selected > 0) {
                            selected = selected - 1;
                        }
                    }

                    return EventResult.reject;
                }

                edited(text) => {
                    root.search-changed(text);
                }

                accepted() => {
                    root.accepted();
                }
            }

            ScrollView {
                VerticalBox {
                    spacing: 5px;
                    for action[idx] in actions: Rectangle {
                        // min-height: idx == 0 ? 60px : 40px;
                        max-height: Theme.max-height;
                        background: idx == selected ? Theme.option-color-selected : Theme.option-color;
                        border-radius: Theme.option-border-radius;
                    
                        TouchArea {
                            clicked => {
                                root.action-clicked(idx);
                            }
                        }
                    
                        VerticalBox {
                            padding: 12px;
                            Text {
                                text: action.name;
                                font-size: Theme.name-font-size;
                                font-weight: 600;
                                color: idx == selected ? Theme.name-font-color-selected : Theme.name-font-color;
                                wrap: word-wrap;
                            }
                            if (Theme.exec-show): Text {
                                text: action.exec;
                                font-size: Theme.exec-font-size;
                                color: idx == selected ? Theme.exec-font-color-selected : Theme.exec-font-color;
                                wrap: word-wrap;

                            }
                        }
                    }
                }
            }
        }
    }
}
