export global Theme {
	// WINDOW STUFF
	in-out property <length> width: 600px;
	in-out property <length> height: 400px;
	
	in-out property <color> background-color: #a1a1a1;
	in-out property <length> border-radius: 15px;

	// ACTION STUFF
	in-out property <length> max-height: 60px;
	in-out property <color> option-color: #f0f0f0;
	in-out property <color> option-color-selected: #e0e0e0;
	in-out property <length> option-border-radius: 8px;

	in-out property <length> name-font-size: 16px;
	in-out property <length> exec-font-size: 12px;
	in-out property <bool> exec-show: true;
}
